In [14]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [15]:
df = pd.read_csv("news_categories.csv")
df.head()

,category,news,summary
0,business,Ad sales boost Time Warner profit\n\nQuarterly...,TimeWarner said fourth quarter sales rose 2% t...
1,business,Dollar gains on Greenspan speech\n\nThe dollar...,The dollar has hit its highest level against t...
2,business,Yukos unit buyer faces loan claim\n\nThe owner...,Yukos' owner Menatep Group says it will ask Ro...
3,business,High fuel prices hit BA's profits\n\nBritish A...,"Rod Eddington, BA's chief executive, said the ..."
4,business,Pernod takeover talk lifts Domecq\n\nShares in...,Pernod has reduced the debt it took on to fund...

In [16]:
df.info()
df=df.drop(["news"],axis=1)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2225 entries, 0 to 2224
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   category  2225 non-null   object
 1   news      2225 non-null   object
 2   summary   2225 non-null   object
dtypes: object(3)
memory usage: 52.3+ KB

In [17]:
#Encoding labels
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df["category"] = encoder.fit_transform(df["category"])
df.head()

   category                                            summary
0         0  TimeWarner said fourth quarter sales rose 2% t...
1         0  The dollar has hit its highest level against t...
2         0  Yukos' owner Menatep Group says it will ask Ro...
3         0  Rod Eddington, BA's chief executive, said the ...
4         0  Pernod has reduced the debt it took on to fund...

In [18]:
#Dropped news
df = df.rename(columns={"summary":"news"})
df.head()

   category                                               news
0         0  TimeWarner said fourth quarter sales rose 2% t...
1         0  The dollar has hit its highest level against t...
2         0  Yukos' owner Menatep Group says it will ask Ro...
3         0  Rod Eddington, BA's chief executive, said the ...
4         0  Pernod has reduced the debt it took on to fund...

In [46]:
df["news"] = df["news"].fillna("").astype(str)
X=df["news"]

news = X.tolist()
tokenizer = Tokenizer(num_words=10000)
tokenizer.fit_on_texts(news)

word_index = tokenizer.word_index
vocab_size = len(word_index)
sequences = tokenizer.texts_to_sequences(news)
X = pad_sequences(sequences,maxlen=500,padding='post',truncating='post')

y=df["category"]
X_train, X_test, y_train, y_test = train_test_split(
    X, y, 
    test_size=0.2,      # Proportion of the dataset to use for testing (e.g., 20%)
    random_state=42,    # Ensures reproducibility
    stratify=y          # Ensures equal/proportional split based on labels
)

In [47]:
#Embedding
embedding_index={}
embedding_dim = 50
with open ("Downloads/glove.6B/glove.6B.50d.txt",'r',encoding='utf-8') as f:
    for line in f:
        values = line.split()
        word = values[0]
        coefs = np.asarray(values[1:],dtype='float32')
        embedding_index[word] = coefs
    embedding_matrix = np.zeros((vocab_size, embedding_dim))
    for word,i in word_index.items():
        if i<vocab_size:
            embedding_vector=embedding_index.get(word)
            if embedding_vector is not None:
                embedding_matrix[i]=embedding_vector

In [50]:
num_classes = len(np.unique(y_train))
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(
        input_dim=embedding_matrix.shape[0],
        output_dim=embedding_matrix.shape[1],
        weights=[embedding_matrix],
        trainable=False
    ),
    tf.keras.layers.SpatialDropout1D(0.2),
    tf.keras.layers.Conv1D(
        filters=128,
        kernel_size=5,
        activation="relu",
        padding="same"
    ),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.MaxPooling1D(pool_size=2),
    tf.keras.layers.Bidirectional(
        tf.keras.layers.LSTM(128, return_sequences=True)
    ),
    tf.keras.layers.GlobalMaxPooling1D(),
    tf.keras.layers.Dense(128, activation="relu"),
    tf.keras.layers.Dropout(0.4),
    tf.keras.layers.Dense(
        num_classes,
        activation="softmax"
    )
])
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.0005),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_8 (Embedding)              │ ?                           │       1,091,600 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ spatial_dropout1d (SpatialDropout1D) │ ?                           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv1d_6 (Conv1D)                    │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization                  │ ?                           │     0 (unbuilt) │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling1d_6 (MaxPooling1D)       │ ?                           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ bidirectional (Bidirectional)        │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ global_max_pooling1d                 │ ?                           │               0 │
│ (GlobalMaxPooling1D)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_6 (Dense)                      │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_6 (Dropout)                  │ ?                           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_7 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,091,600 (4.16 MB)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 1,091,600 (4.16 MB)

In [51]:
history = model.fit(
    np.array(X_train), 
    np.array(y_train), 
    epochs=50, 
    validation_data=(np.array(X_test), np.array(y_test)), 
    verbose=2
)

Epoch 1/50
56/56 - 16s - 294ms/step - accuracy: 0.5612 - loss: 1.1833 - val_accuracy: 0.8854 - val_loss: 0.9721
Epoch 2/50
56/56 - 13s - 241ms/step - accuracy: 0.8635 - loss: 0.4643 - val_accuracy: 0.8966 - val_loss: 0.4208
Epoch 3/50
56/56 - 13s - 230ms/step - accuracy: 0.8994 - loss: 0.3105 - val_accuracy: 0.9438 - val_loss: 0.3009
Epoch 4/50
56/56 - 13s - 229ms/step - accuracy: 0.9135 - loss: 0.2667 - val_accuracy: 0.9461 - val_loss: 0.1875
Epoch 5/50
56/56 - 13s - 225ms/step - accuracy: 0.9180 - loss: 0.2383 - val_accuracy: 0.9528 - val_loss: 0.1475
Epoch 6/50
56/56 - 13s - 234ms/step - accuracy: 0.9337 - loss: 0.2099 - val_accuracy: 0.9640 - val_loss: 0.1234
Epoch 7/50
56/56 - 13s - 228ms/step - accuracy: 0.9371 - loss: 0.1810 - val_accuracy: 0.9640 - val_loss: 0.1218
Epoch 8/50
56/56 - 13s - 233ms/step - accuracy: 0.9399 - loss: 0.1692 - val_accuracy: 0.9528 - val_loss: 0.1282
Epoch 9/50
56/56 - 13s - 229ms/step - accuracy: 0.9438 - loss: 0.1736 - val_accuracy: 0.9663 - val_loss: 0.1352
Epoch 10/50
56/56 - 13s - 231ms/step - accuracy: 0.9438 - loss: 0.1483 - val_accuracy: 0.9663 - val_loss: 0.1180
Epoch 11/50
56/56 - 13s - 236ms/step - accuracy: 0.9545 - loss: 0.1436 - val_accuracy: 0.9685 - val_loss: 0.1098
Epoch 12/50
56/56 - 14s - 245ms/step - accuracy: 0.9652 - loss: 0.1053 - val_accuracy: 0.9708 - val_loss: 0.1089
Epoch 13/50
56/56 - 15s - 260ms/step - accuracy: 0.9618 - loss: 0.1245 - val_accuracy: 0.9685 - val_loss: 0.0844
Epoch 14/50
56/56 - 13s - 236ms/step - accuracy: 0.9697 - loss: 0.1069 - val_accuracy: 0.9730 - val_loss: 0.0839
Epoch 15/50
56/56 - 13s - 237ms/step - accuracy: 0.9725 - loss: 0.0895 - val_accuracy: 0.9663 - val_loss: 0.0973
Epoch 16/50
56/56 - 13s - 235ms/step - accuracy: 0.9691 - loss: 0.0820 - val_accuracy: 0.9708 - val_loss: 0.0850
Epoch 17/50
56/56 - 13s - 239ms/step - accuracy: 0.9708 - loss: 0.0935 - val_accuracy: 0.9708 - val_loss: 0.0879
Epoch 18/50
56/56 - 14s - 254ms/step - accuracy: 0.9719 - loss: 0.0796 - val_accuracy: 0.9663 - val_loss: 0.1279
Epoch 19/50
56/56 - 14s - 243ms/step - accuracy: 0.9725 - loss: 0.0705 - val_accuracy: 0.9708 - val_loss: 0.0821
Epoch 20/50
56/56 - 13s - 236ms/step - accuracy: 0.9758 - loss: 0.0684 - val_accuracy: 0.9685 - val_loss: 0.1001
Epoch 21/50
56/56 - 14s - 245ms/step - accuracy: 0.9713 - loss: 0.0876 - val_accuracy: 0.9663 - val_loss: 0.1083
Epoch 22/50
56/56 - 13s - 240ms/step - accuracy: 0.9781 - loss: 0.0652 - val_accuracy: 0.9753 - val_loss: 0.0804
Epoch 23/50
56/56 - 13s - 233ms/step - accuracy: 0.9843 - loss: 0.0536 - val_accuracy: 0.9685 - val_loss: 0.1021
Epoch 24/50
56/56 - 13s - 237ms/step - accuracy: 0.9854 - loss: 0.0436 - val_accuracy: 0.9618 - val_loss: 0.1548
Epoch 25/50
56/56 - 13s - 232ms/step - accuracy: 0.9803 - loss: 0.0530 - val_accuracy: 0.9663 - val_loss: 0.1052
Epoch 26/50
56/56 - 14s - 244ms/step - accuracy: 0.9860 - loss: 0.0388 - val_accuracy: 0.9640 - val_loss: 0.1115
Epoch 27/50
56/56 - 13s - 234ms/step - accuracy: 0.9899 - loss: 0.0349 - val_accuracy: 0.9663 - val_loss: 0.1213
Epoch 28/50
56/56 - 13s - 230ms/step - accuracy: 0.9848 - loss: 0.0392 - val_accuracy: 0.9708 - val_loss: 0.1008
Epoch 29/50
56/56 - 13s - 238ms/step - accuracy: 0.9837 - loss: 0.0525 - val_accuracy: 0.9708 - val_loss: 0.0964
Epoch 30/50
56/56 - 13s - 233ms/step - accuracy: 0.9843 - loss: 0.0447 - val_accuracy: 0.9730 - val_loss: 0.0900
Epoch 31/50
56/56 - 13s - 234ms/step - accuracy: 0.9882 - loss: 0.0343 - val_accuracy: 0.9708 - val_loss: 0.1187
Epoch 32/50
56/56 - 13s - 237ms/step - accuracy: 0.9888 - loss: 0.0349 - val_accuracy: 0.9753 - val_loss: 0.0886
Epoch 33/50
56/56 - 13s - 237ms/step - accuracy: 0.9921 - loss: 0.0258 - val_accuracy: 0.9685 - val_loss: 0.1197
Epoch 34/50
56/56 - 13s - 235ms/step - accuracy: 0.9916 - loss: 0.0361 - val_accuracy: 0.9618 - val_loss: 0.1363
Epoch 35/50
56/56 - 13s - 234ms/step - accuracy: 0.9916 - loss: 0.0248 - val_accuracy: 0.9753 - val_loss: 0.0979
Epoch 36/50
56/56 - 13s - 231ms/step - accuracy: 0.9910 - loss: 0.0200 - val_accuracy: 0.9685 - val_loss: 0.1257
Epoch 37/50
56/56 - 13s - 233ms/step - accuracy: 0.9899 - loss: 0.0266 - val_accuracy: 0.9663 - val_loss: 0.1398
Epoch 38/50
56/56 - 13s - 234ms/step - accuracy: 0.9961 - loss: 0.0137 - val_accuracy: 0.9663 - val_loss: 0.1310
Epoch 39/50
56/56 - 13s - 233ms/step - accuracy: 0.9933 - loss: 0.0196 - val_accuracy: 0.9730 - val_loss: 0.1130
Epoch 40/50
56/56 - 13s - 231ms/step - accuracy: 0.9910 - loss: 0.0205 - val_accuracy: 0.9663 - val_loss: 0.1173
Epoch 41/50
56/56 - 13s - 239ms/step - accuracy: 0.9938 - loss: 0.0204 - val_accuracy: 0.9663 - val_loss: 0.1237
Epoch 42/50
56/56 - 13s - 235ms/step - accuracy: 0.9910 - loss: 0.0252 - val_accuracy: 0.9798 - val_loss: 0.0734
Epoch 43/50
56/56 - 13s - 235ms/step - accuracy: 0.9938 - loss: 0.0222 - val_accuracy: 0.9730 - val_loss: 0.0866
Epoch 44/50
56/56 - 13s - 238ms/step - accuracy: 0.9944 - loss: 0.0174 - val_accuracy: 0.9775 - val_loss: 0.0906
Epoch 45/50
56/56 - 13s - 239ms/step - accuracy: 0.9933 - loss: 0.0251 - val_accuracy: 0.9685 - val_loss: 0.1385
Epoch 46/50
56/56 - 13s - 239ms/step - accuracy: 0.9944 - loss: 0.0170 - val_accuracy: 0.9663 - val_loss: 0.1483
Epoch 47/50
56/56 - 14s - 243ms/step - accuracy: 0.9944 - loss: 0.0181 - val_accuracy: 0.9640 - val_loss: 0.1518
Epoch 48/50
56/56 - 13s - 234ms/step - accuracy: 0.9961 - loss: 0.0120 - val_accuracy: 0.9596 - val_loss: 0.1270
Epoch 49/50
56/56 - 13s - 231ms/step - accuracy: 0.9949 - loss: 0.0170 - val_accuracy: 0.9730 - val_loss: 0.1118
Epoch 50/50
56/56 - 13s - 230ms/step - accuracy: 0.9983 - loss: 0.0077 - val_accuracy: 0.9708 - val_loss: 0.1116

In [53]:
from sklearn.metrics import classification_report
import numpy as np

predictions = model.predict(X_test)
predicted_classes = np.argmax(predictions, axis=1)

print(classification_report(
    np.array(y_test),
    predicted_classes,
    target_names=encoder.classes_
))

14/14 ━━━━━━━━━━━━━━━━━━━━ 1s 84ms/step
               precision    recall  f1-score   support

     business       0.98      0.93      0.95       102
entertainment       0.95      0.99      0.97        77
     politics       0.96      0.95      0.96        84
        sport       1.00      1.00      1.00       102
         tech       0.95      0.99      0.97        80

     accuracy                           0.97       445
    macro avg       0.97      0.97      0.97       445
 weighted avg       0.97      0.97      0.97       445

In [55]:
loss, accuracy = model.evaluate(
    X_test,
    np.array(y_test),
    verbose=0
)

print("Test Accuracy:", accuracy)

Test Accuracy: 0.9707865118980408

In [56]:
model.save("news_category_model.keras")